### ISSUE TITLE
关于设备适配问题

### ISSUE THREAD

**Issue by SuzukiHonoka** [hanwckf/padavan-4.4#2]
我可以把之前repo中的templates和board的配置放到这边吗？是否可以兼容？感谢一直以来的贡献ww。

**Comment by paldier** [comment]
不能，新内核使用dts配置

**Comment by hanwckf** [comment]
> 我可以把之前repo中的templates和board的配置放到这边吗？是否可以兼容？感谢一直以来的贡献ww。

除了软件包相关的选项可以适用，内核配置（kernel-4.4.x.config）要重新生成，并且要给对应的机型加上[dts文件](https://github.com/hanwckf/padavan-4.4/tree/main/trunk/linux-4.4.x/arch/mips/boot/dts/ralink)

**Comment by SuzukiHonoka** [comment]
感谢二位的回复！

**Comment by bishiping** [comment]
> > 我可以把之前repo中的templates和board的配置放到这边吗？是否可以兼容？感谢一直以来的贡献ww。
> 
> 除了软件包相关的选项可以适用，内核配置（kernel-4.4.x.config）要重新生成，并且要给对应的机型加上[dts文件](https://github.com/hanwckf/padavan-4.4/tree/main/trunk/linux-4.4.x/arch/mips/boot/dts/ralink)

大佬，不好意思挖坟了，感谢长期以来的贡献。
请问要怎么生成内核配置以及dts文件呢？我的路由器型号是B70，之前3.3项目支持，到4.4就找不到了，网上也找不到教程。刷的别人编译的4.4的固件，不太满意，有不少不想用的插件。
