### ISSUE TITLE
通过无线突然上不了网

### ISSUE THREAD

**Issue by muziling** [hanwckf/padavan-4.4#21]
内核里一直在打印这种错误
Feb 18 17:11:43 kernel: AndesMTPciKickOutCmdMsg FreeNum == 0 (TxCpuIdx = 127, TxDmaIdx = 0, TxSwFreeIdx = 0)
Feb 18 17:11:43 kernel: kick out msg fail

**Comment by muziling** [comment]
版本号 4.4.3.9-100_d96689c

**Comment by hanwckf** [comment]
这个错误是什么在路由器的什么工作情况下出现的？能不能每次都复现？

**Comment by muziling** [comment]
k2p_nano 刷机后大概20个小时后出现， 我再看看这几天会不会再次出现。

**Comment by ningsibuqu** [comment]
同样 k2p_nano，刷到现在运行1天 18时了，没问题。

**Comment by muziling** [comment]
这么多天没再出现。 无法复现，关闭关闭
